BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Bathroom";
CREATE TABLE "Bathroom" ("id" INTEGER PRIMARY KEY ,"eng" VARCHAR,"vn" VARCHAR DEFAULT (null) , "phatam" VARCHAR, "yeuthich" INTEGER, "hinhanh" INTEGER);
INSERT INTO "Bathroom" VALUES(1,'bathtub','bồn tắm','/ˈbɑːθ.tʌb/',0,NULL);
INSERT INTO "Bathroom" VALUES(2,'soap','xà phòng','/səʊp/',0,NULL);
INSERT INTO "Bathroom" VALUES(3,'shower','vòi tắm hoa sen','/ʃaʊəʳ/',0,NULL);
INSERT INTO "Bathroom" VALUES(4,'sink','bồn rửa mặt','/sɪŋk/',0,NULL);
INSERT INTO "Bathroom" VALUES(5,'faucet','vòi','/ˈfɔː.sɪt/',0,NULL);
INSERT INTO "Bathroom" VALUES(6,'toilet','

bệ xí','/ˈtɔɪ.lət/',0,NULL);
INSERT INTO "Bathroom" VALUES(7,'shampoo','dầu gội đầu','/ʃæmˈpuː/',0,NULL);
INSERT INTO "Bathroom" VALUES(8,'toilet paper','giấy vệ sinh','/ˈtɔɪ.lət ˈpeɪ.pəʳ/',0,NULL);
INSERT INTO "Bathroom" VALUES(9,'toilet brush','bàn chải bệ xí','/ˈtɔɪ.lət brʌʃ/',0,NULL);
INSERT INTO "Bathroom" VALUES(10,'plunger','cái thụt bệ xí','/ˈplʌn.dʒəʳ/',0,NULL);
INSERT INTO "Bathroom" VALUES(11,'tissue','khăn giấy','/ˈtɪs.juː/',0,NULL);
INSERT INTO "Bathroom" VALUES(12,'marble','đá hoa','/ˈmɑː.bl/',0,NULL);
INSERT INTO "Bathroom" VALUES(13,'towel','khăn tắm','/taʊəl/',0,NULL);
INSERT INTO "Bathroom" VALUES(14,'hairbrush','bàn chải tóc','/ˈheə.brʌʃ/',0,NULL);
INSERT INTO "Bathroom" VALUES(15,'comb','cái lược','/kəʊm/',0,NULL);
INSERT INTO "Bathroom" VALUES(16,'mirror','gương','/ˈmɪr.əʳ/',0,NULL);
INSERT INTO "Bathroom" VALUES(17,'hair dryer','máy sấy tóc','/her ˈdraɪ.əʳ/',0,NULL);
INSERT INTO "Bathroom" VALUES(18,'perfume','nước hoa','/pərˈfjuːm/',0,NULL);
INSERT INTO "Bathroom" VALUES(19,'deodorant','chất khử mùi','/diˈəʊ.dər.ənt/',0,NULL);
INSERT INTO "Bathroom" VALUES(20,'lipstick','son môi','/ˈlɪp.stɪk/',0,NULL);
INSERT INTO "Bathroom" VALUES(21,'toothbrush','bàn chải đánh răng','/ˈtuːθ.brʌʃ/',0,NULL);
INSERT INTO "Bathroom" VALUES(22,'nail polish','sơn móng tay','/neɪl ˈpɒl.ɪʃ/',0,NULL);
INSERT INTO "Bathroom" VALUES(23,'mascara','thuốc bôi mi mắt','/mæsˈkɑː.rə/',0,NULL);
INSERT INTO "Bathroom" VALUES(24,'eye liner','chì kẻ mắt','/aɪ ˈlaɪ.nəʳ/',0,NULL);
INSERT INTO "Bathroom" VALUES(25,'powder','phấn','/ˈpaʊ.dəʳ/',0,NULL);
INSERT INTO "Bathroom" VALUES(26,'floss','chỉ nha khoa (để làm sạch răng)','/flɒs/',0,NULL);
INSERT INTO "Bathroom" VALUES(27,'toothpaste','kem đánh răng','/ˈtuːθ.peɪst/',0,NULL);
INSERT INTO "Bathroom" VALUES(28,'razor','dao cạo','/ˈreɪ.zəʳ/',0,NULL);
INSERT INTO "Bathroom" VALUES(29,'razor blade','lưỡi dao cạo','/ˈreɪ.zəʳ bleɪd/',0,NULL);
INSERT INTO "Bathroom" VALUES(30,'tweezers','cái nhíp','/ˈtwiː.zəz/',0,NULL);
INSERT INTO "Bathroom" VALUES(31,'shaving cream','kem cạo râu','/ˈʃeɪ.vɪŋ kriːm/',0,NULL);
INSERT INTO "Bathroom" VALUES(32,'nail clippers ','bấm móng tay','/neɪl ˈklɪp.əz/',0,NULL);
INSERT INTO "Bathroom" VALUES(33,'hairspray','keo xịt tóc','/herspreɪ/',0,NULL);
INSERT INTO "Bathroom" VALUES(34,'cotton swab','bông ngoáy tai','/ˈkɒt.ən swɒb/',0,NULL);
INSERT INTO "Bathroom" VALUES(35,'medicine cabinet','tủ thuốc','/ˈmed.ɪ.sən ˈkæb.ɪ.nət/',0,NULL);
COMMIT;
